alpha: 0.2
bs: 256
comment: ''
dataset: SMD
dropout: 0.3
dynamic_pot: false
epochs: 30
fc_hid_dim: 150
fc_n_layers: 3
feat_gat_embed_dim: null
gamma: 1
group: 1-1
gru_hid_dim: 150
gru_n_layers: 1
init_lr: 0.001
kernel_size: 7
level: null
log_tensorboard: true
lookback: 100
normalize: true
print_every: 1
q: null
recon_hid_dim: 150
recon_n_layers: 1
scale_scores: false
shuffle_dataset: true
spec_res: false
time_gat_embed_dim: null
use_cuda: true
use_gatv2: true
use_mov_av: false
val_split: 0.1
